### ISSUE TITLE
testing with mosquitto_sub/mosquitto_pub

### ISSUE THREAD

**Issue by shilbert01** [maxbachmann-magicmirror2/mqtt-mm2-gateway#1]
I fail to see if I have properly configured the whole thing. It would be nice if you could provide a method for testing (e.g. if the bridge properly registered to the mosquitto server and if it handles incoming requests

Something along the lines of 

    mosquitto_sub 

    mosquitto_pub 

would be nice.

**Comment by maxbachmann** [comment]
thanks for opening the issue. I will look into it.

**Comment by maxbachmann** [comment]
I cleaned up all the code and added comments yesterday. I did add a description on the use of mosquitto_pub aswell.
It correctly receives messages from multiple topics now and can use username and password. I still have to test sending messages with the MMM-HideShowMove module, which is the last part I did not test yet ;)

**Comment by maxbachmann** [comment]
I fixed a couple more small things and the MMM-HideShowMove module receives the message now correctly.
Since you asked for it I did add some additional debug output aswell.

**Comment by maxbachmann** [comment]
I just found that MMM-MQTT has a much better implementation, so I will use it and just change what needs to be different (I did that in the MMM-MQTT branch, but did not test it yet)
